### ISSUE TITLE
Zooming where the cursor at?

### ISSUE THREAD

**Issue by dnylnd** [QuisPic/ae-smooth-zoom#6]
So i really like your zoom script, but when i zoom with the vanilla zooming holding alt it zooms where my cursor at.

but when im zooming with your script it can only zoom in the middle of the comp. it should zoom where my cursor at.

am i missing something?

**Comment by QuisPic** [comment]
Hi, no, that's how the script currently works. After Effects automatically centers the comp view when some script calls the zoom() function, and there is no way to disable this behavior. But I'm actually already working on a fix that will restore the comp position after zooming, so hopefully the next update will fix this issue.

**Comment by dnylnd** [comment]
nice i can't wait! :) thx for the answer!

**Comment by QuisPic** [comment]
Hi, this is now possible in the latest release ([v0.3.0](https://github.com/QuisPic/ae-zoom/releases/tag/v0.3.0)). Make sure to update both the script and the plug-in.
Enable the checkbox in "Zoom Settings -> Experimental -> Maintain View position after zooming" and then under the checkbox select "Cursor Position" in the drop-down menu.

**Comment by dnylnd** [comment]
very nice! its working! i tested it! awesome work!

**Comment by dnylnd** [comment]
hey i noticed something interesting. im working on a 4k project and the default zooming with after effects don't let me zoom more than 800%.

with your script i can zoom 830%. after it jumps back to 800%.

is it possibble to zoom even further? :D
