### ISSUE TITLE
Key Binding, shorcut with scroll mouse not only comp panel?

### ISSUE THREAD

**Issue by alethinh** [QuisPic/ae-smooth-zoom#7]
If use keyshortcut, ctrl or alt with scroll up down, it changes zoom everywhere mouse on screen, default AE only zooms when mouse moves into comp panel

**Comment by QuisPic** [comment]
Hi, this is now fixed in the latest release ([v0.3.0](https://github.com/QuisPic/ae-zoom/releases/tag/v0.3.0)). First, make sure to update both the script and the plug-in. Then enable the checkbox in "Zoom Settings -> Experimental -> Change zoom only when cursor is inside a viewport".

**Comment by alethinh** [comment]
> Hi, this is now fixed in the latest release ([v0.3.0](https://github.com/QuisPic/ae-zoom/releases/tag/v0.3.0)). First, make sure to update both the script and the plug-in. Then enable the checkbox in "Zoom Settings -> Experimental -> Change zoom only when cursor is inside a viewport".

Good jobs, you are amazing
