### ISSUE TITLE
Script error if Viewer window not active

### ISSUE THREAD

**Issue by Joolyan** [QuisPic/ae-smooth-zoom#9]
Minor issue when Viewer window not active when Zoom.jsx is run.

If the Composition Viewer window is not active (e.g. Bodymovin extension is open in Viewer workspace) when launching Zoom.jsx the script errors with "Unable to execute script at line 5911. null is not an object".

Line 5911 is `var zoomValue = app.activeViewer.views[0].options.zoom;` in the updated `Zoom.getViewZoom = function () {...}`

Displaying the Viewer panel and re-launching the script resolves the issue.

Not a major issue, if it's not possible to capture this error.

**Comment by QuisPic** [comment]
Thank you for reporting. This is now fixed in the new release ([v0.3.0.1](https://github.com/QuisPic/ae-zoom/releases/tag/v0.3.0.1))

**Comment by Joolyan** [comment]
Thanks for fixing ...and so quickly.
